### ISSUE TITLE
OTL Wizard Tool - issue concerning attributes of DateTime datatype

### ISSUE THREAD

**Issue by karlvandenabbeele** [davidvlaminck/OTLMOW-GUI#69]
When I perform a data request via DAVIE (see screenshot 'requested_data_davie.png') and upload the requested file containing OTL data into the OTL Wizard Tool, and then export that file again in step 4 'Export asset data', the 'T' (between the date and time) disappears for attributes of the 'DateTime' type (see screenshot 'processed_data_otl_wizard.png'. This ultimately causes an error when the file is submitted via DAVIE.

<img width="330" height="330" alt="Image" src="https://github.com/user-attachments/assets/89ca4be0-3d62-470b-980e-71a7cd61b143" />
<img width="330" height="330" alt="Image" src="https://github.com/user-attachments/assets/5cf7943e-cf0b-4d09-bc11-6b9b19e0eae2" />

**Comment by davidvlaminck** [comment]
Fixed with otlmow-model 2.16.6.0
Just re-open the OTL Wizard, which will automatically download the new model version and this should be fixed.
Can you confirm? @karlvandenabbeele

**Comment by karlvandenabbeele** [comment]
Hi David,

I closed and re-opened the OTL Wizard, but the issue is not solved: the letter 'T' still gets removed.

FYI: I am using the latest version (V1.1) of the OTL Wizard.
